### PR TITLE
Credentials Manager implementation for an encrypted local storage

### LINKED ISSUE #6: Save credentials as an (encrypted) file
In the Twitch login panel, add a button to save the credentials in a file. 

The file could be encrypted for example with [File.open_encrypted()](https://docs.godotengine.org/fr/stable/classes/class_file.html#class-file-method-open-encrypted) or using the [Crypto class](https://docs.godotengine.org/fr/stable/classes/class_crypto.html).

### PR DESCRIPTION
**Pull request by CptFubar**
This credentials manager creates an encrypt key to locally store oauth tokens in binary form. The interface allows for storage or deletion of locally stored credentials.

### CODE REVIEW

**Comment by MrEliptik** [comment]
Thanks for the PR it looks really cool! 

One thing that bugged me. If I connect once entering my credentials manually, it saves the credentials correctly. But then, if I relaunch, I assume the `connect with credentials` button would we activated. From what I've tested it's not. 

So maybe we the function `load_all_credentials` could return a boolean if it finds a credential resource, that way we can enable the button. What do you think? 

I've tried enabling the button manually, and it works great!

**Comment by CptFubar** [comment]
At the moment your login form is pre-filled with your custom username, which in a normal case would be empty. Only after entering the correct username will it match for a existing saved credential and activate the connect with save credentials button.
So the reason for it not working when starting it up with your username is because you are not typing anything in it.

An alternatively method would be to allow to save the current session so it will autoload it in the next time.
What do you think ?

**Comment by MrEliptik** [comment]
I think that for now, we could just remove my username and have a little label that tells you to enter your username. 

I've made those changes and I think it should be good for now. If we find it useful, we could make another change with a proper way of remembering the username and the associated oauth token

**Comment by CptFubar** [comment]
I implemented a session save system that is quite simple. It is just a file (last_session) with the username in it. 
CredentialsManager takes care of the rest (loading in the credentials if it exists and activate the corresponding buttons).

**Review by MrEliptik — APPROVED** [review]
Ok cool, that's perfect! I've tested it and it works just fine. Thanks for your contribution :D

**Pull request merged**
